<a href="https://colab.research.google.com/github/JustTheice/The-Fucking-Homework/blob/main/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [3]:
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [4]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.]), being coerced into generic type (double)

tensor([0., 1., 2.])


In [5]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.randint(low=0, high=10, size=(4,2))

tensor([[1, 6],
        [4, 2],
        [3, 5],
        [2, 7]])

In [9]:
torch.rand(3, 4) # val∈(0,1)

tensor([[0.2225, 0.3574, 0.9956, 0.5579],
        [0.6150, 0.7932, 0.5889, 0.7878],
        [0.8266, 0.1440, 0.0681, 0.6471]])

In [10]:
torch.randn((3,4)) # val ~ N(0,1)

tensor([[ 0.6789,  0.6770,  0.2716, -1.9090],
        [ 0.8410, -0.3629,  1.0755, -0.1161],
        [-0.5198,  0.3723, -0.9937,  1.4524]])

In [13]:
# converting numpyArray into tensor
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
